spring:
  application:
    name: dev_ouk-back

logging:
  level:
    org.springframework.web: INFO
    org.springframework.filter: INFO
    org.springframework.boot.web.servlet: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

info:
  app:
    name: devouk-back
    version: 0.0.1
    description: Dev Ouk Backend Application

app:
  name: Dev Ouk Backend
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:5173"