spring:
  application:
    name: dev_ouk-back

  data:
    redis:
      port: 6379
      host: redis

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.filter: DEBUG
    org.springframework.boot.web.servlet: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always
  health:
    redis:
      enabled: false
info:
  app:
    name: devouk-back
    version: 0.0.1
    description: Dev Ouk Backend Application