package com.devouk.devouk_back.domain.common.exception;

public enum ErrorCode {
  // Member
  MEMBER_NOT_FOUND,
  DUPLICATE_MEMBER,

  // Taxonomy / Term
  TAXONOMY_NOT_FOUND,

  // Problem
  PROBLEM_NOT_FOUND,
  DUPLICATE_PROBLEM,
  PROBLEM_TAG_NOT_FOUND,
  INVALID_PROBLEM_SITE,
  INVALID_PROBLEM_SORT_OPTION,
  UNSUPPORTED_PROBLEM_SITE,
  PROBLEM_PREVIEW_FETCH_FAILED,

  // Attempt
  INVALID_ATTEMPT_VERDICT,
  INVALID_ATTEMPT_VERDICT_FOR_CREATE,
  INVALID_ATTEMPT_LANGUAGE,
  INVALID_ATTEMPT_FAIL_TYPE,

  // AlgoNote
  ALGO_NOTE_NOT_FOUND,
  ALGO_NOTE_TAG_NOT_FOUND,
  DUPLICATE_ALGO_NOTE_SLUG,
  INVALID_ALGO_NOTE_STATUS,
  INVALID_ALGO_NOTE_SORT_OPTION,
  INVALID_ALGO_NOTE_TITLE,

  // Pagination / Range
  INVALID_CURSOR,
  INVALID_CREATED_AT_RANGE
}
